/**
 *
 * Author: david.deng<david.deng@jcinfotech.com>
 * Date: 2018-12-22
 */
const UserTree = {}
const tree = {
    "uid": 5814,
    "name": "邓三",
    "face": "https:\/\/image-cdn.kinwind.com\/Data\/Userface\/5814\/5814_C2232CA4-00C1-D6DF-DD06-228B3008B476.png@150w_150h_1482139163",
    "gender": 1,
    "reality": 1,
    "firstName": "松辉",
    "lastName": "邓",
    "managementuid": 0,
    "relationText": "",
    "identitycode": "A4592E6A-E357-F35C-5FEE-27A0BD8A1DD4",
    "mtime": "1482139163",
    "ctime": "1430715202",
    "root": 1,
    "alias": "",
    "isCoreFamily": 1,
    "hasPet": 0,
    "0": {
        "uid": 8009,
        "name": "邓父亲",
        "face": "https:\/\/image-cdn.kinwind.com\/Data\/Userface\/8009\/8009_yuan_face.jpg@150w_150h_1479373223",
        "gender": 1,
        "reality": 1,
        "firstName": "父亲",
        "lastName": "邓",
        "managementuid": 0,
        "relationId": "18",
        "relation": "FATHER",
        "relationText": "爸爸",
        "identitycode": "F5EB9B1B-D898-DAA7-3CD1-69FE49F3DA20",
        "mtime": "1479373922",
        "ctime": "1479108459",
        "alias": "",
        "isCoreFamily": 0,
        "hasPet": 0,
        "0": {
            "uid": 7963,
            "name": "肥子父亲的父亲 邓",
            "face": "https:\/\/image-cdn.kinwind.com\/Data\/Userface\/7963\/7963_yuan_face.png@150w_150h_1480652054",
            "gender": 1,
            "reality": 0,
            "firstName": "肥子父亲的父亲",
            "lastName": "邓",
            "managementuid": "5814",
            "relationId": "18",
            "relation": "FATHER",
            "relationText": "爸爸",
            "identitycode": "E2E5C89B-1C8A-0219-3466-7D3A29D5EA02",
            "mtime": "1480652054",
            "ctime": "1478228438",
            "alias": "",
            "isCoreFamily": 0,
            "hasPet": 0
        },
        "1": {
            "uid": 8023,
            "name": "儿子99 邓",
            "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/boy_middle_face.jpg",
            "gender": 1,
            "reality": 0,
            "firstName": "儿子99",
            "lastName": "邓",
            "managementuid": "8009",
            "relationId": "4",
            "relation": "SON",
            "relationText": "儿子",
            "identitycode": "5ED38D51-F765-AC47-5482-793F6EB13D28",
            "mtime": "1479373270",
            "ctime": "1479373270",
            "alias": "",
            "isCoreFamily": 0,
            "hasPet": 0
        }
    },
    "1": {
        "uid": 5820,
        "name": "昕昕",
        "face": "https:\/\/image-cdn.kinwind.com\/Data\/Userface\/5820\/5820_yuan_face.png@150w_150h_1457931773",
        "gender": 0,
        "reality": 0,
        "firstName": "昕昕",
        "lastName": "邓",
        "managementuid": "5814",
        "relationId": "7",
        "relation": "DAUGHTER",
        "relationText": "女儿",
        "identitycode": "5E7638AB-A2A8-48E0-AD13-F7F4FCE72FCE",
        "mtime": "1545478451",
        "ctime": "1430726947",
        "alias": "昕昕",
        "isCoreFamily": 1,
        "hasPet": 0,
        "0": {
            "uid": 7508,
            "name": "儿子",
            "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/boy_middle_face.jpg",
            "gender": 1,
            "reality": 0,
            "firstName": "儿子",
            "lastName": "儿子",
            "managementuid": "5814",
            "relationId": "4",
            "relation": "SON",
            "relationText": "儿子",
            "identitycode": "4AD6E83D-AFFD-1260-2259-E0957AFDE916",
            "mtime": "1545408478",
            "ctime": "1469695533",
            "alias": "儿子",
            "isCoreFamily": 0,
            "hasPet": 0,
            "0": {
                "uid": 8383,
                "name": "666",
                "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/boy_middle_face.jpg",
                "gender": 1,
                "reality": 0,
                "firstName": "666",
                "lastName": "儿子",
                "managementuid": "5814",
                "relationId": "4",
                "relation": "SON",
                "relationText": "儿子",
                "identitycode": "76F74496-8555-7D07-8CED-DB3E095613B9",
                "mtime": "1545408462",
                "ctime": "1545408462",
                "alias": "666",
                "isCoreFamily": 0,
                "hasPet": 0
            },
            "1": {
                "uid": 8384,
                "name": "777",
                "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/boy_middle_face.jpg",
                "gender": 1,
                "reality": 0,
                "firstName": "777",
                "lastName": "儿子",
                "managementuid": "5814",
                "relationId": "4",
                "relation": "SON",
                "relationText": "儿子",
                "identitycode": "745627CE-9F03-58DF-4D4E-C395B8F7B778",
                "mtime": "1545408478",
                "ctime": "1545408478",
                "alias": "777",
                "isCoreFamily": 0,
                "hasPet": 0
            },
            "2": {
                "uid": 8030,
                "name": "儿子222",
                "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/boy_middle_face.jpg",
                "gender": 1,
                "reality": 0,
                "firstName": "222",
                "lastName": "儿子",
                "managementuid": "5814",
                "relationId": "4",
                "relation": "SON",
                "relationText": "儿子",
                "identitycode": "7DA44C1F-4E27-CCEA-EB60-10B90B110257",
                "mtime": "1479486250",
                "ctime": "1479486250",
                "alias": "",
                "isCoreFamily": 0,
                "hasPet": 0
            },
            "3": {
                "uid": 8378,
                "name": "111",
                "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/boy_middle_face.jpg",
                "gender": 1,
                "reality": 0,
                "firstName": "111",
                "lastName": "儿子",
                "managementuid": "5814",
                "relationId": "4",
                "relation": "SON",
                "relationText": "儿子",
                "identitycode": "F3F2DC1D-6E6A-32AC-6775-88268206970F",
                "mtime": "1545408390",
                "ctime": "1545408390",
                "alias": "111",
                "isCoreFamily": 0,
                "hasPet": 0
            },
            "4": {
                "uid": 8379,
                "name": "222",
                "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/boy_middle_face.jpg",
                "gender": 1,
                "reality": 0,
                "firstName": "222",
                "lastName": "儿子",
                "managementuid": "5814",
                "relationId": "4",
                "relation": "SON",
                "relationText": "儿子",
                "identitycode": "08C9E720-EF98-5F59-878A-43505C500576",
                "mtime": "1545408404",
                "ctime": "1545408404",
                "alias": "222",
                "isCoreFamily": 0,
                "hasPet": 0
            },
            "5": {
                "uid": 8380,
                "name": "333",
                "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/boy_middle_face.jpg",
                "gender": 1,
                "reality": 0,
                "firstName": "333",
                "lastName": "儿子",
                "managementuid": "5814",
                "relationId": "4",
                "relation": "SON",
                "relationText": "儿子",
                "identitycode": "8467F7F7-3079-FB2C-6557-B170041A47AC",
                "mtime": "1545408417",
                "ctime": "1545408417",
                "alias": "333",
                "isCoreFamily": 0,
                "hasPet": 0
            },
            "6": {
                "uid": 8381,
                "name": "444",
                "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/boy_middle_face.jpg",
                "gender": 1,
                "reality": 0,
                "firstName": "444",
                "lastName": "儿子",
                "managementuid": "5814",
                "relationId": "4",
                "relation": "SON",
                "relationText": "儿子",
                "identitycode": "6E7B28D9-9C2C-EB00-C1BE-AA3E6E5964A7",
                "mtime": "1545408433",
                "ctime": "1545408433",
                "alias": "444",
                "isCoreFamily": 0,
                "hasPet": 0
            },
            "7": {
                "uid": 8382,
                "name": "555",
                "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/boy_middle_face.jpg",
                "gender": 1,
                "reality": 0,
                "firstName": "555",
                "lastName": "儿子",
                "managementuid": "5814",
                "relationId": "4",
                "relation": "SON",
                "relationText": "儿子",
                "identitycode": "32A4AFA8-CBE0-E1C2-C698-30F51379639E",
                "mtime": "1545408446",
                "ctime": "1545408446",
                "alias": "555",
                "isCoreFamily": 0,
                "hasPet": 0
            },
            "8": {
                "uid": 8029,
                "name": "儿子22",
                "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/girl_middle_face.jpg",
                "gender": 0,
                "reality": 0,
                "firstName": "22",
                "lastName": "儿子",
                "managementuid": "5814",
                "relationId": "7",
                "relation": "DAUGHTER",
                "relationText": "女儿",
                "identitycode": "1760B869-C8C2-2409-36DF-23E9EEFB3B2D",
                "mtime": "1479486224",
                "ctime": "1479486224",
                "alias": "",
                "isCoreFamily": 0,
                "hasPet": 0
            }
        },
        "1": {
            "uid": 8385,
            "name": "333123",
            "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/girl_middle_face.jpg",
            "gender": 0,
            "reality": 0,
            "firstName": "123",
            "lastName": "333",
            "managementuid": "5814",
            "relationId": "7",
            "relation": "DAUGHTER",
            "relationText": "女儿",
            "identitycode": "661C9092-4DB8-6D8B-2B86-857418DA9FD3",
            "mtime": "1545478451",
            "ctime": "1545478450",
            "alias": "",
            "isCoreFamily": 0,
            "hasPet": 0
        }
    },
    "2": {
        "uid": 5904,
        "name": "邓大姐",
        "face": "https:\/\/image-cdn.kinwind.com\/Data\/Userface\/5904\/5904_yuan_face.png@150w_150h_1432954448",
        "gender": 0,
        "reality": 1,
        "firstName": "大姐（真实姓名）",
        "lastName": "邓",
        "managementuid": 0,
        "relationId": "38",
        "relation": "SISTER",
        "relationText": "姐或妹",
        "identitycode": "B1EAEA76-59EC-FA8F-57DA-966D84FAFCFC",
        "mtime": "1479108786",
        "ctime": "1432953181",
        "alias": "邓洁梅",
        "isCoreFamily": 0,
        "hasPet": 0,
        "0": {
            "uid": 7984,
            "name": "彭11",
            "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/boy_middle_face.jpg",
            "gender": 1,
            "reality": 0,
            "firstName": "11",
            "lastName": "彭",
            "managementuid": "5904",
            "relationId": "4",
            "relation": "SON",
            "relationText": "儿子",
            "identitycode": "B431BA2E-3249-81B0-E556-E26D17AB9760",
            "mtime": "1478586568",
            "ctime": "1478586441",
            "alias": "",
            "isCoreFamily": 0,
            "hasPet": 0
        },
        "1": {
            "uid": 5905,
            "name": "彭22",
            "face": "https:\/\/image-cdn.kinwind.com\/Data\/Userface\/5905\/5905_yuan_face.png@150w_150h_1433152991",
            "gender": 1,
            "reality": 0,
            "firstName": "22",
            "lastName": "彭",
            "managementuid": "5814",
            "relationId": "4",
            "relation": "SON",
            "relationText": "儿子",
            "identitycode": "B92794A1-F4E2-36C6-A67B-07FC222FE9E3",
            "mtime": "1477561393",
            "ctime": "1432953216",
            "alias": "彭22",
            "isCoreFamily": 0,
            "hasPet": 0
        },
        "2": {
            "uid": 5906,
            "name": "彭父亲",
            "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/boy_middle_face.jpg",
            "gender": 1,
            "reality": 0,
            "firstName": "父亲",
            "lastName": "彭",
            "managementuid": "5814",
            "relationId": "2",
            "relation": "HUSBAND",
            "relationText": "丈夫",
            "identitycode": "241E9CCB-3B82-50D1-8549-25D4601690BE",
            "mtime": "1477561393",
            "ctime": "1432953286",
            "alias": "彭父亲",
            "isCoreFamily": 0,
            "hasPet": 0,
            "0": {
                "uid": 5930,
                "name": "家姐老爷",
                "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/boy_middle_face.jpg",
                "gender": 1,
                "reality": 0,
                "firstName": "xx",
                "lastName": "彭",
                "managementuid": "5814",
                "relationId": "18",
                "relation": "FATHER",
                "relationText": "爸爸",
                "identitycode": "FC28E50E-1384-52ED-940D-3B2ECC88335D",
                "mtime": "1477561393",
                "ctime": "1432997231",
                "alias": "家姐家公",
                "isCoreFamily": 0,
                "hasPet": 0
            }
        }
    },
    "3": {
        "uid": 5910,
        "name": "二姐",
        "face": "https:\/\/image-cdn.kinwind.com\/Data\/Userface\/5910\/5910_yuan_face.png@150w_150h_1432954552",
        "gender": 0,
        "reality": 0,
        "firstName": "二姐",
        "lastName": "冼",
        "managementuid": 0,
        "relationId": "38",
        "relation": "SISTER",
        "relationText": "姐或妹",
        "identitycode": "93F42F72-D618-0018-68FB-46E2E087DD0B",
        "mtime": "1477561393",
        "ctime": "1432953506",
        "alias": "二姐",
        "isCoreFamily": 0,
        "hasPet": 0,
        "0": {
            "uid": 5914,
            "name": "姐夫",
            "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/boy_middle_face.jpg",
            "gender": 1,
            "reality": 0,
            "firstName": "成",
            "lastName": "丘",
            "managementuid": "5814",
            "relationId": "2",
            "relation": "HUSBAND",
            "relationText": "丈夫",
            "identitycode": "958AE066-D004-66D5-651A-6C93A560571C",
            "mtime": "1477561393",
            "ctime": "1432953887",
            "alias": "姐夫",
            "isCoreFamily": 0,
            "hasPet": 0
        }
    },
    "4": {
        "uid": 5827,
        "name": "冼小姐（真实姓名）",
        "face": "https:\/\/image-cdn.kinwind.com\/Data\/Userface\/5827\/5827_yuan_face.jpg@150w_150h_1430979520",
        "gender": 0,
        "reality": 1,
        "firstName": "冼小姐（真实姓名）",
        "lastName": "冼",
        "managementuid": 0,
        "relationId": "3",
        "relation": "WIFE",
        "relationText": "妻子",
        "identitycode": "397ED1D1-7792-41DC-8186-5A3C027BDCCD",
        "mtime": "1482139837",
        "ctime": "1430979517",
        "alias": "",
        "isCoreFamily": 1,
        "hasPet": 0,
        "0": {
            "uid": 7964,
            "name": "冼胜",
            "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/boy_middle_face.jpg",
            "gender": 1,
            "reality": 0,
            "firstName": "胜",
            "lastName": "冼",
            "managementuid": "5827",
            "relationId": "18",
            "relation": "FATHER",
            "relationText": "爸爸",
            "identitycode": "FE09DF0B-1C8E-6682-0217-C44037A3B399",
            "mtime": "1479108786",
            "ctime": "1478228546",
            "alias": "",
            "isCoreFamily": 0,
            "hasPet": 0
        },
        "1": {
            "uid": 5900,
            "name": "妈",
            "face": "https:\/\/image-cdn.kinwind.com\/Data\/Userface\/5900\/5900_yuan_face.png@150w_150h_1433150910",
            "gender": 0,
            "reality": 1,
            "firstName": "金好",
            "lastName": "江",
            "managementuid": 0,
            "relationId": "19",
            "relation": "MOTHER",
            "relationText": "妈妈",
            "identitycode": "67031933-6683-6F34-652C-ED15AB953FBF",
            "mtime": "1479108786",
            "ctime": "1432952784",
            "alias": "妈",
            "isCoreFamily": 0,
            "hasPet": 0,
            "0": {
                "uid": 5915,
                "name": "老婆舅父",
                "face": "https:\/\/image-cdn.kinwind.com\/Data\/Userface\/5915\/5915_yuan_face.png@150w_150h_1433151427",
                "gender": 1,
                "reality": 0,
                "firstName": "xx",
                "lastName": "江",
                "managementuid": "5814",
                "relationId": "34",
                "relation": "BROTHER",
                "relationText": "哥或弟",
                "identitycode": "BEA45E1C-3E73-FC74-8074-25E70D643E3B",
                "mtime": "1477561393",
                "ctime": "1432995732",
                "alias": "老婆舅父",
                "isCoreFamily": 0,
                "hasPet": 0,
                "0": {
                    "uid": 5917,
                    "name": "老婆表哥",
                    "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/boy_middle_face.jpg",
                    "gender": 1,
                    "reality": 0,
                    "firstName": "明",
                    "lastName": "江",
                    "managementuid": "5814",
                    "relationId": "4",
                    "relation": "SON",
                    "relationText": "儿子",
                    "identitycode": "562E1875-8B10-F778-390A-23F3A5419982",
                    "mtime": "1477561393",
                    "ctime": "1432995828",
                    "alias": "老婆表哥",
                    "isCoreFamily": 0,
                    "hasPet": 0
                },
                "1": {
                    "uid": 5932,
                    "name": "江小姐",
                    "face": "https:\/\/image-cdn.kinwind.com\/Data\/Userface\/5932\/5932_yuan_face.png@150w_150h_1433153359",
                    "gender": 0,
                    "reality": 1,
                    "firstName": "",
                    "lastName": "",
                    "managementuid": 0,
                    "relationId": "7",
                    "relation": "DAUGHTER",
                    "relationText": "女儿",
                    "identitycode": "DA12DE98-8FB8-2B9C-F548-A079CEADA986",
                    "mtime": "1477561393",
                    "ctime": "1433145806",
                    "alias": "江小姐",
                    "isCoreFamily": 0,
                    "hasPet": 0,
                    "0": {
                        "uid": 7891,
                        "name": "江小姐女 江",
                        "face": "https:\/\/www.kinwind.com\/Data\/Userface\/0\/girl_middle_face.jpg",
                        "gender": 0,
                        "reality": 0,
                        "firstName": "江小姐女",
                        "lastName": "江",
                        "managementuid": "5932",
                        "relationId": "7",
                        "relation": "DAUGHTER",
                        "relationText": "女儿",
                        "identitycode": "39E446F3-4547-ACB0-E643-AD493254D815",
                        "mtime": "1477561393",
                        "ctime": "1477537734",
                        "alias": "",
                        "isCoreFamily": 0,
                        "hasPet": 0
                    }
                }
            },
            "1": {
                "uid": 5902,
                "name": "老婆外婆",
                "face": "https:\/\/image-cdn.kinwind.com\/Data\/Userface\/5902\/5902_yuan_face.jpg@150w_150h_1450148689",
                "gender": 0,
                "reality": 0,
                "firstName": "婆",
                "lastName": "外",
                "managementuid": "5814",
                "relationId": "19",
                "relation": "MOTHER",
                "relationText": "妈妈",
                "identitycode": "B1C07A86-A072-BB8E-6FD5-CE4114433737",
                "mtime": "1477561393",
                "ctime": "1432952876",
                "alias": "老婆外婆",
                "isCoreFamily": 0,
                "hasPet": 0
            }
        }
    }
};

function setTree(parentTree, subTree) {
    let sub: any[] = [];
    Object.keys(subTree).forEach(key => {
        let obj: any = subTree[key];
        let k = Number(key);
        if (isNaN(k)) {
            if (['uid', 'name'].indexOf(key) > -1) {
                parentTree[key] = obj
            }
        } else {
            sub.push(obj);
        }
    });
    if (sub.length > 0) {
        parentTree['sub'] = [];
        sub.forEach(_subTree => {
            let subObj = {};
            setTree(subObj, _subTree);
            parentTree['sub'].push(subObj);
        })
    }
}

setTree(UserTree, tree);


export default UserTree
